### ISSUE TITLE
Search button replaces typed input with current location

### ISSUE THREAD

**Issue by damianochintala** [mwelwankuta/weatherapp#1]
### Description:
When using the search feature in the weather app, typing a new city and country gets overwritten by the user's current location after pressing the search button. This is likely caused by the `fetchLocation` function being called every time the city or country state changes in the `useEffect` hook.

### Steps to Reproduce:
1. Open the app.
2. Manually enter a new city and country in the search fields.
3. Press the search button.
4. The manually entered city and country are replaced with the user's current location.

### Expected Behavior:
The city and country entered by the user should not be replaced with the current location when performing a search.

### Suggested Fix:
Consider separating the `fetchLocation` function from the weather-fetching logic. The `fetchLocation` should only run once when the component mounts, and not on every state change.

**Comment by mwenku** [comment]
@damianochintala  thanks for the reporting the issue. resolving it...
